// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkd_6sW5jsjU7IwV40xU09NdfAafXe70',
    appId: '1:365906131724:web:bcea25d851dc453ac12729',
    messagingSenderId: '365906131724',
    projectId: 'chat-bloc-app',
    authDomain: 'chat-bloc-app.firebaseapp.com',
    storageBucket: 'chat-bloc-app.appspot.com',
    measurementId: 'G-KSJQ0ZN95Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PKswog9t57yoQtn99IDiGrVKggOfOdI',
    appId: '1:365906131724:android:d6058b584ee0fab5c12729',
    messagingSenderId: '365906131724',
    projectId: 'chat-bloc-app',
    storageBucket: 'chat-bloc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVCZdyl43T24i19KHaZnjUUME8R3kHKY',
    appId: '1:365906131724:ios:681afd26e0d458d9c12729',
    messagingSenderId: '365906131724',
    projectId: 'chat-bloc-app',
    storageBucket: 'chat-bloc-app.appspot.com',
    androidClientId: '365906131724-j9u07bmgdrp9b661kihd3it9pp3fuhvs.apps.googleusercontent.com',
    iosClientId: '365906131724-ip15e3cv482bgvj7ccf11p9stkerkf8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBlocApp',
  );
}
